### ISSUE TITLE
Automatically hard wrap lines

### ISSUE THREAD

**Issue by ncuillery** [BedrockStreaming/tech.bedrockstreaming.com#118]
Pair review would be easier if the lines were hard wrapped. Finding a single word with a typo in a 15-lines block is annnoying.

![image](https://cloud.githubusercontent.com/assets/4425455/12548040/f57ba482-c353-11e5-968a-41bb6b6c1876.png)

It also avoids huuuuge extracts for each comments (Github displays few previous lines that can take the entire height of the screen).

**Comment by ncuillery** [comment]
To do that:
- Sublim: https://github.com/randy3k/AutoWrap
- Atom: https://discuss.atom.io/t/automatically-hard-wrap-lines/8986
- Webstorm / Phpstorm: https://devnet.jetbrains.com/message/5309062

**Comment by Oliboy50** [comment]
I think this has been "fixed"  since the "suggestions as commit" GitHub feature has been released.

If something think this is still an issue, feel free to reopen.
